### ISSUE TITLE
Submit a ticket

### ISSUE THREAD

**Issue by btchoum** [btchoum/aspnetcore-service-desk#1]
As a user, I want to be able to submit a ticket.

The following fields can be provided when submitting a ticket:

**Required Fields:**
- Title
- Description
- Total number of users impacted
- Submitter Email Address
- Submitter Name

**Optional Fields:**
- Date the issue started

**Task List:**
- [x] Design Ticket Submission page
- [x] Implement Ticket Submission page/controller
- [x] Add Data Access Layer
- [x] Create database
- [x] Add Integration Tests
