### ISSUE TITLE
Send Email when ticket created

### ISSUE THREAD

**Issue by btchoum** [btchoum/aspnetcore-service-desk#5]
As a user who submitted a ticket, I want to get a confirmation email with the ticket number, so that I know that my ticket was received. The email should contain the ticket number and a hyperlink to the ticket.

**Task List**

- [ ] Create email sender component
- [ ] Hook it up to ticket submission
- [ ] Emails should not always be sent when testing locally
